In [1]:
import h5py
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import pprint
import pickle
import yaml
import json

In [2]:
from ModuleLibrary.utils import load_data_HS
test = load_data_HS(301,50)

chr10.npy
(135534747, 4) (135534747,)
chr11.npy
(135006516, 4) (135006516,)
chr12.npy
(133851895, 4) (133851895,)
chr13.npy
(115169878, 4) (115169878,)
chr14.npy
(107349540, 4) (107349540,)
chr15.npy
(102531392, 4) (102531392,)
chr16.npy
(90354753, 4) (90354753,)
chr17.npy
(81195210, 4) (81195210,)
chr18.npy
(78077248, 4) (78077248,)
chr19.npy
(59128983, 4) (59128983,)
chr2.npy
(243199373, 4) (243199373,)
chr20.npy
(63025520, 4) (63025520,)
chr21.npy
(48129895, 4) (48129895,)
chr22.npy
(51304566, 4) (51304566,)
chr3.npy
(198022430, 4) (198022430,)
chr4.npy
(191154276, 4) (191154276,)
chr5.npy
(180915260, 4) (180915260,)
chr6.npy
(171115067, 4) (171115067,)
chr7.npy
(159138663, 4) (159138663,)
chr8.npy
(146364022, 4) (146364022,)
chr9.npy
(141213431, 4) (141213431,)
chrX.npy
(155270560, 4) (155270560,)
chrY.npy
(59373566, 4) (59373566,)
(2846430091, 301, 4, 1) int8
(2846430091,) int8


In [7]:
string = 'my number is 254 or 45'
lst = string.split(' ')
res = 0
for el in lst:
    try:
        res += int(el)
        
    except:
        continue
print(res)

299


In [6]:
import numpy as np
test = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(test)
print(test[::-1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [7]:
from ModuleLibrary.utils import get_complementary_strand_OH
test2 = get_complementary_strand_OH(test)

In [8]:
print(test2)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [4]:
print(data.shape, data.dtype)
print(labels.shape, labels.dtype)
print(indexes.shape, indexes.dtype)
print(ratio)

(5928340673, 2000, 4, 1) int8
(5928340672,) int8
(59282950,) int64
3.0117931917951815


In [8]:
def test(x):
    for i in range(0,x,2):
        yield i

In [10]:
print(list(test(10)))

[0, 2, 4, 6, 8]


In [11]:
for i in test(50):
    print(i)

0
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
